-- Phase 2 logical schema — CockroachDB dialect (also usable via Spanner's
-- PostgreSQL interface through PGAdapter, per runbook §Phase 2).
-- Column names/order are kept identical across schema_pg.sql,
-- schema_mysql.sql, and schema_googlesql.sql so experiments/02_query_execution/query.sql
-- can be ported verbatim across engines.
--
-- Not required for this to run (defaultdb always exists), but the tables
-- get their own database instead of cluttering defaultdb, and it keeps
-- this file parallel to schema_mysql.sql.

CREATE DATABASE IF NOT EXISTS seminar;
USE seminar;

-- === Banking (Exp 3 transactions, Exp 4 write-skew is separate table below,
--     Exp 7 benchmark) ===

CREATE TABLE accounts (
    id      INT8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    owner   STRING NOT NULL,
    balance DECIMAL(15,2) NOT NULL,
    region  STRING NOT NULL
);

CREATE TABLE ledger (
    id         INT8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    from_acct  INT8 NOT NULL REFERENCES accounts(id),
    to_acct    INT8 NOT NULL REFERENCES accounts(id),
    amount     DECIMAL(15,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- === E-commerce (Exp 1 distribution, Exp 2 query execution, Exp 8 standouts) ===

CREATE TABLE customers (
    id         INT8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       STRING NOT NULL,
    email      STRING NOT NULL,
    region     STRING NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE products (
    id       INT8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name     STRING NOT NULL,
    category STRING NOT NULL,
    price    DECIMAL(10,2) NOT NULL,
    rating   DECIMAL(2,1) NOT NULL
);

CREATE TABLE orders (
    id          INT8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id INT8 NOT NULL REFERENCES customers(id),
    order_date  TIMESTAMPTZ NOT NULL DEFAULT now(),
    total       DECIMAL(12,2) NOT NULL
);

-- NOTE: on Spanner (schema_googlesql.sql) this table is INTERLEAVE IN PARENT
-- orders for the Exp 8 locality demo, which forces its primary key to be
-- (order_id, id) instead of a bare id. Kept as a single-column id here and
-- in MySQL for dialect parity elsewhere; the asymmetry is intentional and
-- recorded in experiments/08_standouts/exp8_compatibility.md.
CREATE TABLE order_items (
    id         INT8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id   INT8 NOT NULL REFERENCES orders(id),
    product_id INT8 NOT NULL REFERENCES products(id),
    quantity   INT8 NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL
);

-- === Doctors (Exp 4 write-skew) ===
-- ids are seeded explicitly as 1..10 (not identity) so ids 1 and 2 can be
-- pinned as the two on-call doctors per the runbook's write-skew setup.

CREATE TABLE doctors (
    id      INT8 PRIMARY KEY,
    name    STRING NOT NULL,
    on_call BOOL NOT NULL DEFAULT false
);
